// ThemePaletteSO.cs  -  Assets/_Project/Scripts/Data
// Inspectable palette asset for designers; generated by the build tool.
using System.Collections.Generic;
using UnityEngine;

[System.Serializable] public class NamedColor { public string name; public Color color = Color.white; }

[CreateAssetMenu(fileName = "ThemePalette", menuName = "Puppeteer/Theme Palette")]
public class ThemePaletteSO : ScriptableObject { public List<NamedColor> swatches = new List<NamedColor>(); }
